kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: oes-analysis-for-canary
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: oes-analysis-for-canary
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          application: uniqueapps
          profile: opsmx-profile-v3
          user: admin
          lifetimeMinutes: 3
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: demoservice
            logTemplateName: stacktemplate
            logScopeVariables: "resource.labels.container_name"
            baselineLogScope: "issuegen-prod"
            canaryLogScope: "issuegen-prod"
