apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: oes-analysis-isd
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: oes-analysis-isd
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          profile: opsmx-profile-v3
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          application: negative-tests
          user: admin
          lifetimeMinutes: 3
          baselineStartTime: "2022-10-04T10:10:09.0000Z"
          canaryStartTime: "2022-10-04T10:13:09.0000Z"
          threshold:
            pass: 80
            marginal: 60
          services:
          - logTemplateName: stacktemplatenoregex
            logScopeVariables: "resource.labels.container_name"
            baselineLogScope: "sd-ss1-canary-67d9ddfb45-d7c92"
            canaryLogScope: "sd-ss1-canary-67d9ddfb45-d7c92"
          - logTemplateName: stacktemplateregex
            logScopeVariables: "resource.labels.pod_name"
            baselineLogScope: "sd-ss1-canary-*-d7c92"
            canaryLogScope: "sd-ss1-canary-*-d7c92"
