kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: sj-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: sj-analysis
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          profile: opsmx-profile-v3
          application: final-tests
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          user: admin
          intervalTime: 3
          lookBackType: growing
          lifetimeMinutes: 3
          threshold:
            pass: 90
            marginal: 65
          globalMetricTemplate: prometheusverification
          globalLogTemplate: testingUI
          services:
          - logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: ".*{{args.baseline-hash}}.*"
            canaryLogScope: ".*{{args.canary-hash}}.*"
