kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: sj-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: sj-analysis
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          profile: opsmx-profile
          gateUrl: https://argoqa-helm.isd-dev.opsmx.net/
          application: final-tests
          user: admin
          lifetimeMinutes: 3
          threshold:
            pass: 80
            marginal: 60
          globalMetricTemplate: prometheusverification
          globalLogTemplate: logtemp
          services:
          - metricTemplateName: newreliccustomrollout
            metricTemplateVersion: "v2.0"
            metricScopeVariables: "${app_key},${host_key}"
            baselineMetricScope: "issuegen-ss1,.*{{args.baseline-hash}}.*"
            canaryMetricScope: "issuegen-ss1,.*{{args.canary-hash}}.*"
