kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: sj-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: sj-analysis
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          profile: opsmx-profile
          gateUrl: https://argoqa-helm.isd-dev.opsmx.net/ 
          application: final-tests
          user: admin
          intervalTime: 3
          lookBackType: "growing"
          lifetimeMinutes: 6
          threshold:
            pass: 80
            marginal: 60
          globalMetricTemplate: prometheusverification
          globalLogTemplate: testLogTemplateName65998
          services:
          - logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: ".*{{args.baseline-hash}}.*"
            canaryLogScope: ".*{{args.canary-hash}}.*"
            logTemplateVersion: "v5.0"
