kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: sj-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: sj-analysis
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          profile: opsmx-profile-v3
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          application: final-tests
          user: admin
          lifetimeMinutes: 12
          intervalTime: 3
          lookBackType: "growing"
          threshold:
            pass: 80
            marginal: 60
          globalMetricTemplate: prometheusverification
          globalLogTemplate: logtemp
          services:
          - metricScopeVariables: "${namespace_key},${pod_key}"
            baselineMetricScope: "argocd,{{args.baseline-hash}}"
            canaryMetricScope: "argocd,{{args.canary-hash}}"
            metricTemplateName: "missionfailmetric"
