apiVersion: v1
kind: ConfigMap
metadata:
  name: metrixtemplate
data: 
 Template: ISDTemplate
 TemplateType: Metric
 Json: |
  {
   "filterKey": "${namespace_key},${pod_key},${app_name}",
   "data": {
     "percent_diff_threshold": "hard",
      "isNormalize": false,
      "groups": [
      {
        "metrics": [
          {
            "metricType": "ADVANCED",
            "metricWeight": 1,
            "nanStrategy": "Remove",
            "accountName": "isd312-saas-prom",
            "riskDirection": "HigherOrLower",
            "customThresholdHigher": 10,
            "name": "sum(container_memory_usage_bytes{namespace=\"${namespace_key}\", pod=~\".*${pod_key}.*\"})",
            "criticality": "Normal",
            "customThresholdLower": 10,
            "watchlist": false
          }
        ],
        "group": "Memory Usage By Pod Name"
      }
    ]
  },
  "templateName": "metrixtemplate",
  "advancedProvider": "PROMETHEUS"
  }
