apiVersion: v1
kind: ConfigMap
metadata:
  name: metrixy
data: 
 Template: ISDTemplate
 TemplateType: Metric
 Json: |
  {
   "filterKey": "${namespace_key},${pod_key},${app_name}",
   "data": {
     "percent_diff_threshold": "hard",
      "isNormalize": false,
      "groups": [
    ]
  },
  "templateName": "metrixy",
  "advancedProvider": "PROMETHEUS"
  }
