apiVersion: v1
kind: ConfigMap
metadata:
  name: testingsrikanth
data: 
 Template: ISDTemplate
 TemplateType: LOG
 Json: |
   {
    "templateName": "testingsrikanth",
    "monitoringProvider": "ELASTICSEARCH",
    "accountName": "logEalastic1",
    "index": "kubernetes*",
    "filterKey": "kubernetes.pod_name",
    "tags": [
    {
      "string": "JunaidError",
      "tag": "Hello",
      "id": ""
    }
      ],
    "errorTopics": [
    {
      "string": "WARNING",
      "topic": "WARN",
      "type": "default"
    }
    ],
    "responseKeywords": "log"
    }
