apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: job412-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: job412-analysis-score
      initialDelay: 60s
      provider:
        job:
          spec:
            backoffLimit: 2
            template:
              spec:
                serviceAccountName: opsmx-provider-acc
                imagePullSecrets:
                - name: opsmx11-secret
                containers:
                - name: junaid-job-analysis
                  image: genos1998/argojob:v43
                  imagePullPolicy: Always
                  env:
                    - name: MY_POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: STABLE_POD_HASH
                      value: "{{args.baseline-hash}}"
                    - name: LATEST_POD_HASH
                      value: "{{args.canary-hash}}"
                  volumeMounts:
                    - name: provider-config-volume
                      mountPath: /etc/config/provider
                    - name: gitopstemplates
                      mountPath: /etc/config/templates
                    - name: secret-config-volume
                      mountPath: /etc/config/secrets
                      readOnly: true
                restartPolicy: Never
                volumes:
                - name: provider-config-volume
                  configMap:
                    name: job412-analysis-config
                - name: gitopstemplates
                  projected:
                    sources:
                    - configMap:
                        name: elasticasy-verifier
                    - configMap:
                        name: promy
                    - configMap:
                        name: promxy-global
                    - configMap:
                        name: prometheus-app-health-generic-min
                - name: secret-config-volume
                  secret:
                    secretName: isd-demo-cd-profile
                    optional: false
