apiVersion: v1
kind: ConfigMap
metadata:
  name: another-analysis-config
data:
  providerConfig: |
    application: prom-test
    lifetimeMinutes: 3
    gitops: true
    passScore: 90
    serviceList: 
    - metricScopeVariables: "variable1"
      baselineMetricScope: "service:baseapp"
      canaryMetricScope: "service:canaryapp"
      metricTemplateName: prometheus-app-health-generic-min
      elasticasy-verifierss
