apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticas-verifier
data:
  elasticas-verifier: |
    monitoringProvider: ELASTICSEARCH
    accountName: logEalastic1
    index: kubernetes*
    responseKeywords: log
    errorTopics:
    - errorString: OnOutOfMemoryError
      topic: IGNORE
