apiVersion: v1
kind: ConfigMap
metadata:
  name: job412-analysis-config
data:
  providerConfig: |
    application: job412
    baselineStartTime: "2022-12-16T10:46:07Z"
    canaryStartTime: "2022-12-16T10:46:07Z"
    lifetimeMinutes: 3
    gitops: TRUE
    passScore: 90
    serviceList: 
    - logScopeVariables: "kubernetes.pod_name"
      baselineLogScope: ".*{{env.STABLE_POD_HASH}}.*"
      canaryLogScope: ".*{{env.LATEST_POD_HASH}}.*"
      logTemplateName: "elasticasy-verifier"
      metricTemplateName: "promy"
      metricScopeVariables: "${namespace_key},${pod_key}"
      baselineMetricScope: "argocd,{{env.STABLE_POD_HASH}}"
      canaryMetricScope: "argocd,{{env.LATEST_POD_HASH}}"
    - metricTemplateName: "promxy-global"
      metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
      baselineMetricScope: "argocd,.*{{env.STABLE_POD_HASH}}.*,job412"
      canaryMetricScope: "argocd,.*{{env.LATEST_POD_HASH}}.*,job412"
    - metricTemplateName: "prometheus-app-health-generic-min"
      metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
      baselineMetricScope: "argocd,.*{{env.STABLE_POD_HASH}}.*,job412"
      canaryMetricScope: "argocd,.*{{env.LATEST_POD_HASH}}.*,job412"
