apiVersion: v1
kind: ConfigMap
metadata:
  name: job412-analysis-config
data:
  providerConfig: |
    Applications: job412
    LifetimeMinutes: 3
    getops: yes
    passScore: 90
    serviceList: 
    - metricTemplateNameS: "prometheus-app-health-generic-min"
      metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
      baselineMetricScope: "argocd,.*{{env.MY_POD_NAME}}.*,job412"
      canaryMetricScope: "argocd,.*{{env.LATEST_POD_HASH}}.*,job412"
    - logScopeVariables: "kubernetes.pod_name"
      baselineLogScope: ".*{{env.MY_POD_NAME}}.*"
      canaryLogScope: ".*{{env.MY_POD_NAME}}.*"
      logTemplateName: "elasticasy-verifierss"
