apiVersion: v1
kind: ConfigMap
metadata:
  name: job412-analysis-config
data:
  providerConfig: |
    application: job412
    baselineStartTime: "2022-12-16T10:46:07Z"
    canaryStartTime: "2022-12-16T10:46:07Z"
    lifetimeMinutes: 3
    gitops: TRUE
    passScore: 90
    serviceList: 
    - logScopeVariables: "resource.labels.pod_name"
      baselineLogScope: ".*{{env.STABLE_POD_HASH}}.*"
      canaryLogScope: ".*{{env.LATEST_POD_HASH}}.*"
      logTemplateName: "stackdriver-generic-minimal"
