apiVersion: v1
kind: ConfigMap
metadata:
  name: job412-analysis-config
data:
  providerConfig: |
    application: job412
    lifetimeMinutes: 4
    intervalTime: 3
    lookBackType: sliding
    gitops: TRUE
    passScore: 90
    baselineStartTime: 
    canaryStartTime: 
    serviceList: 
    - logScopeVariables: "kubernetes.pod_name"
      baselineLogScope: ".*9b5c99749.*"
      canaryLogScope: ".*6fd4f58868.*"
      logTemplateName: "elastic-verifier"
