apiVersion: v1
kind: ConfigMap
metadata:
  name: job412-analysis-config
data:
  providerConfig: |
    application: job412
    lifetimeMinutes: 3
    gitops: False
    passScore: 90
    serviceList: 
    - logScopeVariables: "kubernetes.pod_name"
      baselineLogScope: ".*{{env.STABLE_POD_HASH}}.*"
      canaryLogScope: ".*{{env.LATEST_POD_HASH}}.*"
      logTemplateName: logTemp1
    - metricScopeVariables: "${namespace_key},${pod_key}"
      baselineMetricScope: "argocd,ab"
      canaryMetricScope: "argocd,cd"
      metricTemplateName: "test-prometheus" 
