apiVersion: v1
kind: ConfigMap
metadata:
  name: job412-analysis-config
data:
  providerConfig: |
    application: job412
    lifetimeMinutes: 3
    gitops: TRUE
    passScore: 90
    serviceList: 
    - logScopeVariables: "kubernetes.pod_name"
      baselineLogScope: ".*{{env.STABLE_POD_HASH}}.*"
      canaryLogScope: ".*{{env.LATEST_POD_HASH}}.*"
      logTemplateName: "elasticas-verifier"
    - metricScopeVariables: "${namespace_key},${pod_key}"
      baselineMetricScope: "argocd,{{env.STABLE_POD_HASH}}"
      canaryMetricScope: "argocd,{{env.LATEST_POD_HASH}}"
      metricTemplateName: "prom" 
    - metricScopeVariables: "${namespace_key},${pod_key}"
      baselineMetricScope: "argocd,{{env.STABLE_POD_HASH}}"
      canaryMetricScope: "argocd,{{env.LATEST_POD_HASH}}"
      metricTemplateName: "prom" 
      logScopeVariables: "kubernetes.pod_name"
      baselineLogScope: ".*{{env.STABLE_POD_HASH}}.*"
      canaryLogScope: ".*{{env.LATEST_POD_HASH}}.*"
      logTemplateName: "elasticas-verifier"
      
