apiVersion: v1
kind: ConfigMap
metadata:
  name: job412-analysis-config
data:
  providerConfig: |
    application: job412
    lifetimeMinutes: 3
    gitops: TRUE
    passScore: 90
    serviceList: 
    - metricScopeVariables: "${app_key},${host_key}"
      baselineMetricScope: "job412,.*{{env.STABLE_POD_HASH}}.*"
      canaryMetricScope: "job412,.*{{env.LATEST_POD_HASH}}.*"
      metricTemplateName: "newrelic-app-health-generic-min"
