apiVersion: v1
kind: ConfigMap
metadata:
  name: job412-analysis-config
data:
  providerConfig: |
    application: job412
    lifetimeMinutes: 3
    gitops: yes
    passScore: 90
    serviceList: 
    - metricTemplateName: "prometheus-app-health-generic-min"
      metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
      baselineMetricScope: "argocd,.*{{env.MY_POD_NAME}}.*,job412"
      canaryMetricScope: "argocd,.*{{env.LATEST_POD_HASH}}.*,job412"
