apiVersion: v1
kind: ConfigMap
metadata:
  name: job412-analysis-config
data:
  providerConfig: |
    application: job412
    lifetimeMinutes: 4
    intervalTime: 3
    lookBackType: sliding
    gitops: TRUE
    passScore: 90
    serviceList: 
    - logScopeVariables: "kubernetes.pod_name"
      baselineLogScope: ".*{{env.STABLE_POD_HASH}}.*"
      canaryLogScope: ".*{{env.LATEST_POD_HASH}}.*"
      logTemplateName: "elastic-verifier"
    - metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
      baselineMetricScope: "argocd,{{env.STABLE_POD_HASH}},jobv412"
      canaryMetricScope: "argocd,{{env.LATEST_POD_HASH}},jobv412"
      metricTemplateName: "metricyml" 
