apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: newjob412
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newjob412
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus_io_path: /mgmt/prometheus
        prometheus_io_port: '8088'
      labels:
        app: newjob412
    spec:
      containers:
        - name: job412-ctr
          image: quay.io/opsmxpublic/canary-issuegen:issue-canary-gen-1405
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          env:
            - name: NEWRELIC_LICENSE
              value: 68b87ee3618f714a039cead822d6d250b54dNRAL
            - name: SERVICE_NAME
              value: job412
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 15s }
        - experiment:
            templates:
              - name: job412-analysis
            
