apiVersion: v1
kind: ConfigMap
metadata:
  name: stackdriver-generic-minimal
data:
  stackdriver-generic-minimal: |
    monitoringProvider: STACKDRIVER
    accountName: oes-cluster-sd
    filterKey: resource.labels.pod_name
    responseKeywords: textPayload
    errorTopics: 
    - errorString: ArrayIndexOutOfBounds
      topic: ERROR
    - errorString: NullPointerException
      topic: ERROR
    tags:
    - errorString: FATAL
      tag: FatalErrors
