apiVersion: v1
kind: ConfigMap
metadata:
  name: stackdriver-generic-minimal
data:
  stackdriver-generic-minimal: |
    monitoringProvider: STACKDRIVER
    accountName: oes-cluster-sd
    filterKey: resource.labels.pod_name
    responseKeywords: textPayload
