apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: junaid-job-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: junaid-job-analysis
      provider:
        job:
          spec:
            backoffLimit: 2
            template:
              spec:
                serviceAccountName: job-acc
                containers:
                - name: junaid-job-analysis
                  image: 'genos1998/argojob:v8'
                  env:
                    - name: MY_POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: STABLE_POD_HASH
                      value: "{{args.baseline-hash}}"
                    - name: LATEST_POD_HASH
                      value: "{{args.canary-hash}}"
                    - name: PROVIDER_CONFIG
                      value: providerConfig
                  volumeMounts:
                    - name: provider-config-volume
                      mountPath: /etc/config/provider
                    - name: secret-config-volume
                      mountPath: /etc/config/secrets
                      readOnly: true
                restartPolicy: Never
                volumes:
                - name: provider-config-volume
                  configMap:
                    name: opsmx-provider-config
                - name: secret-config-volume
                  secret:
                    secretName: opsmx-profile-v5
                    optional: false
