apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config
data:
  providerConfig: |
    application: final-job
    user: admin
    opsmxIsdUrl: 'https://isd-argocd.isd-dev.opsmx.net/'
    lifetimeMinutes: 3
    passScore: 90
    serviceList: 
    - - logScopeVariables: "kubernetes.pod_name"
      baselineLogScope: ".*{{env.Stable_Hash}}.*"
      canaryLogScope: ".*{{env.Latest_Hash}}.*"
      logTemplateName: "logtesting"
