apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config
data:
  providerConfig: |
    application: final-job
    user: admin
    opsmxIsdUrl: 'https://isd-dev.argo-dev.opsmx.net/'
    lifetimeMinutes: 4
    intervalTime: 3
    lookBackType: sliding
    gitops: TRUE
    passScore: 90
    serviceList: 
    - metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
      baselineMetricScope: "argocd,{{env.STABLE_POD_HASH}},demoapp-issuegen"
      canaryMetricScope: "argocd,{{env.LATEST_POD_HASH}},demoapp-issuegen"
      metricTemplateName: "metricyml" 
