apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: junaid-job-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: junaid-job-analysis
      initialDelay: 120s
      provider:
        job:
          spec:
            backoffLimit: 2
            template:
              spec:
                serviceAccountName: job-acc
                imagePullSecrets:
                - name: opsmx11-secret
                containers:
                - name: junaid-job-analysis
                  image: 'genos1998/argojob:v19' 
                  imagePullPolicy: Always
                  env:
                    - name: MY_POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: STABLE_POD_HASH
                      value: "{{args.baseline-hash}}"
                    - name: LATEST_POD_HASH
                      value: "{{args.canary-hash}}"
                  volumeMounts:
                    - name: provider-config-volume
                      mountPath: /etc/config/provider
                    - name: gitopstemplates
                      mountPath: /etc/config/templates
                    - name: secret-config-volume
                      mountPath: /etc/config/secrets
                      readOnly: true
                restartPolicy: Never
                volumes:
                - name: provider-config-volume
                  configMap:
                    name: opsmx-provider-config
                - name: gitopstemplates
                  projected:
                    sources:
                    - configMap:
                        name: metrixtemplates
                    - configMap:
                        name: loggytemplate
                    - configMap:
                        name: stacky-map-v3
                    - configMap:
                        name: newnew
                    - configMap:
                        name: yamala
                - name: secret-config-volume
                  secret:
                    secretName: opsmx-profile-isd-demo
                    optional: false
