apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config
data:
  providerConfig: |
    application: final-job
    user: admin
    gateUrl: 'https://isd-dev.argo-dev.opsmx.net/'
    lifetimeMinutes: 4
    intervalTime: 3
    lookBackType: sliding
    gitops: False
    passScore: 90
    serviceList: 
    - metricScopeVariables: "${namespace_key},${pod_key}"
      baselineMetricScope: "argocd,{{args.baseline-hash}}"
      canaryMetricScope: "argocd,{{args.canary-hash}}"
      metricTemplateName: "missionfailmetric"

