apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config
data:
  providerConfig: |
    application: final-job
    user: admin
    gateUrl: 'https://isd-dev.argo-dev.opsmx.net/'
    lifetimeMinutes: 3
    intervalTime: 3
    lookBackType: sliding
    globalLogTemplate: loggytemp
    passScore: 95
    marginalScore: 95
    serviceList:
    - logScopeVariables: "kubernetes.pod_name"
      baselineLogScope: ".*{{env.STABLE_POD_HASH}}.*"
      canaryLogScope: ".*{{env.LATEST_POD_HASH}}.*"
    - logScopeVariables: "kubernetes.pod_name"
      baselineLogScope: ".*{{env.STABLE_POD_HASH}}.*"
      canaryLogScope: ".*{{env.LATEST_POD_HASH}}.*"
      metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
      baselineMetricScope: "argocd,{{env.STABLE_POD_HASH}},demoapp-issuegen"
      canaryMetricScope: "argocd,{{env.LATEST_POD_HASH}},demoapp-issuegen"
      metricTemplateName: "PrometheusMetricTemplate" 
