apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config
data:
  providerConfig: |
    application: justhere
    user: admin
    opsmxIsdUrl: 'https://isd-argocd.isd-dev.opsmx.net/'
    lifetimeMinutes: 3
    passScore: 90
    serviceList: 
    - logScopeVariables: "kubernetes.pod_name"
      baselineLogScope: ".*{{env.STABLE_POD_HASH}}.*"
      canaryLogScope: ".*{{env.LATEST_POD_HASH}}.*"
      logTemplateName: "logtesting"
