apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config
data:
  providerConfig: |
    application: final-job
    user: admin
    gateUrl: 'https://isd-demo.argo-dev.opsmx.net/'
    lifetimeMinutes: 4
    intervalTime: 3
    lookBackType: sliding
    gitops: False
    passScore: 90
    serviceList: 
    - metricScopeVariables: "${namespace_key},${pod_key},${container_key},${app_key}"
      baselineMetricScope: "argocd,boom,blue,orange"
      canaryMetricScope: "argocd,bham,black,yorange"
      metricTemplateName: "prometheus-jvm-health-validator-s"

