apiVersion: v1
kind: ConfigMap
metadata:
  name: logyml
data:
  logyml: |
    monitoringProvider: ELASTICSEARCH
    accountName: logEalastic1
    scoringAlgorithm: Canary
    index: kubernetes*
    responseKeywords: log
    disableDefaultErrorTopics: false
    tags:
    - errorString: NOnOutOfMemoryError
      tag: NotJunaid
    errorTopics:
    - errorString: OnOutOfMemoryError
      topic: CRITICAL
      type: NotSodefault
