apiVersion: v1
kind: ConfigMap
metadata:
  name: logymla
data:
  logymla: |
    monitoringProvider: ELASTICSEARCH
    accountName: logEalastic1
    scoringAlgorithm: Canary
    index: kubernetes*
    responseKeywords: log
