apiVersion: v1
kind: Service
metadata:
  name: junaid-on-job
  namespace: argo-rollouts 
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: junaid-on-job
