apiVersion: v1
kind: ConfigMap
metadata:
  name: yamala
data:
  yamala: |
    monitoringProvider: ELASTICSEARCH
    accountName: logEalastic1
    scoringAlgorithm: Canary
    index: kubernetes*
    responseKeywords: log
    errorTopics:
    - errorString: OnOutOfMemoryError
      topic: CRITICAL
      type: NotSodefault
