apiVersion: v1
kind: ConfigMap
metadata:
  name: yamala
data:
  yamala: |
    monitoringProvider: ELASTICSEARCH
    accountName: logEalastic1
    disableDefaultErrorTopics: yes
    scoringAlgorithm: Canary
    index: kubernetes*
    responseKeywords: log
    tags:
    - errorString: NonOutofMemory
      tag: No
    errorTopics:
    - errorString: OnOutOfMemoryError
      topic: CRITICAL
      type: NotSodefault
