apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: opsmxJob-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
      valueFrom:
        secretKeyRef:
          name: opsmx-secret
          key: opsmxIsdUrl
  metrics:
    - name: opsmxJob-analysis
      provider:
        job:
          spec:
            backoffLimit: 2
            template:
              spec:
                serviceAccountName: opsmx-provider-acc
                imagePullSecrets:
                - name: opsmx11-secret
                containers:
                - name: opsmxJob-analysis
                  image: docker.io/opsmx11/argo-isd-metric-provider-job:v1.2.4 
                  imagePullPolicy: Always
                  env:
                    - name: MY_POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: STABLE_POD_HASH
                      value: "{{args.baseline-hash}}"
                    - name: LATEST_POD_HASH
                      value: "{{args.canary-hash}}"
                  volumeMounts:
                    - name: provider-config-volume
                      mountPath: /etc/config/provider
                    - name: gitopstemplates
                      mountPath: /etc/config/templates
                    - name: secret-config-volume
                      mountPath: /etc/config/secrets
                      readOnly: true
                restartPolicy: Never
                volumes:
                - name: provider-config-volume
                  configMap:
                    name: another-analysis-config
                - name: gitopstemplates
                  projected:
                    sources:
                    - configMap:
                        name: prometheus-app-health-generic-min
                    - configMap:
                        name: elasticasy-verifierssy
                - name: secret-config-volume
                  secret:
                    secretName: opsmx-secret
                    optional: false   
