apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: opsmxjob-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: opsmxjob-analysis
      provider:
        job:
          spec:
            backoffLimit: 2
            template:
              spec:
                serviceAccountName: opsmx-provider-acc
                imagePullSecrets:
                - name: opsmx11-secret
                containers:
                - name: opsmxjob-analysis
                  image: quay.io/opsmxpublic/argo-isd-metric-provider-job:v1.2.5
                  imagePullPolicy: Always
                  env:
                    - name: APP_NAME
                      valueFrom:
                        configMapKeyRef:
                          name: another-analysis-config1
                          key: argocd_argoproj_io_instance
                    - name: MY_POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: STABLE_POD_HASH
                      value: "{{args.baseline-hash}}"
                    - name: LATEST_POD_HASH
                      value: "{{args.canary-hash}}"
                  volumeMounts:
                    - name: provider-config-volume
                      mountPath: /etc/config/provider
                    - name: gitopstemplates
                      mountPath: /etc/config/templates
                    - name: secret-config-volume
                      mountPath: /etc/config/secrets
                      readOnly: true
                restartPolicy: Never
                volumes:
                - name: provider-config-volume
                  configMap:
                    name: another-analysis-config1
                - name: gitopstemplates
                  projected:
                    sources:
                    - configMap:
                        name: prometheus-app-health-generic-min1
                    - configMap:
                        name: elastic-verifier
                - name: secret-config-volume
                  secret:
                    secretName: opsmx-secret
                    optional: false   
