apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-verifier
data:
  elastic-verifier: |
    monitoringProvider: ELASTICSEARCH
    accountName: Elasticsearch
    scoringAlgorithm: Canary
    index: issuegenargo-demo-*
    responseKeywords: log,message
